export default [
  {
    displayName: 'Dewey Klein MD',
    picture: 'https://cdn.fakercloud.com/avatars/themikenagle_128.jpg',
    lastMessage: 'solar cooker',
    lastTime: '10:49 p.m.',
  },
  {
    displayName: 'Lowell Hansen',
    picture: 'https://cdn.fakercloud.com/avatars/hota_v_128.jpg',
    lastMessage: 'attic fan',
    lastTime: '04:28 a.m.',
  },
  {
    displayName: 'Connie Labadie',
    picture: 'https://cdn.fakercloud.com/avatars/lowie_128.jpg',
    lastMessage: 'home server',
    lastTime: '11:19 a.m.',
  },
  {
    displayName: 'Debra Daugherty',
    picture: 'https://cdn.fakercloud.com/avatars/unterdreht_128.jpg',
    lastMessage: 'food steamer',
    lastTime: '07:45 p.m.',
  },
  {
    displayName: 'Joseph Hilpert',
    picture: 'https://cdn.fakercloud.com/avatars/nilshoenson_128.jpg',
    lastMessage: 'waffle iron',
    lastTime: '05:38 p.m.',
  },
  {
    displayName: 'Irene Muller',
    picture: 'https://cdn.fakercloud.com/avatars/amandabuzard_128.jpg',
    lastMessage: 'embroidery machine',
    lastTime: '07:49 p.m.',
  },
  {
    displayName: 'Sean Considine',
    picture: 'https://cdn.fakercloud.com/avatars/hanna_smi_128.jpg',
    lastMessage: 'radiator',
    lastTime: '01:18 p.m.',
  },
  {
    displayName: 'Rhonda Murray',
    picture: 'https://cdn.fakercloud.com/avatars/themikenagle_128.jpg',
    lastMessage: 'set-n-forget cooker',
    lastTime: '01:27 p.m.',
  },
  {
    displayName: 'Miss Armando Rutherford',
    picture: 'https://cdn.fakercloud.com/avatars/sachacorazzi_128.jpg',
    lastMessage: 'fan heater',
    lastTime: '07:57 p.m.',
  },
  {
    displayName: 'Marian Barton',
    picture: 'https://cdn.fakercloud.com/avatars/stefanozoffoli_128.jpg',
    lastMessage: 'espresso machine',
    lastTime: '11:46 a.m.',
  },
  {
    displayName: 'Stephanie Lang',
    picture: 'https://cdn.fakercloud.com/avatars/amayvs_128.jpg',
    lastMessage: 'sump pump',
    lastTime: '11:07 p.m.',
  },
  {
    displayName: 'Alma Douglas',
    picture: 'https://cdn.fakercloud.com/avatars/poormini_128.jpg',
    lastMessage: 'swamp cooler',
    lastTime: '05:23 p.m.',
  },
  {
    displayName: 'Ms. Ella Boyle',
    picture: 'https://cdn.fakercloud.com/avatars/andrea211087_128.jpg',
    lastMessage: 'fan heater',
    lastTime: '08:19 p.m.',
  },
  {
    displayName: 'Elaine Dietrich',
    picture: 'https://cdn.fakercloud.com/avatars/pehamondello_128.jpg',
    lastMessage: 'thermal mass refrigerator',
    lastTime: '09:55 p.m.',
  },
  {
    displayName: 'Vivian Osinski',
    picture: 'https://cdn.fakercloud.com/avatars/vj_demien_128.jpg',
    lastMessage: 'toaster',
    lastTime: '04:37 a.m.',
  },
  {
    displayName: 'Shane Howe',
    picture: 'https://cdn.fakercloud.com/avatars/cdavis565_128.jpg',
    lastMessage: 'field kitchen',
    lastTime: '09:11 a.m.',
  },
  {
    displayName: 'Cristina Fadel',
    picture: 'https://cdn.fakercloud.com/avatars/benjamin_knight_128.jpg',
    lastMessage: 'microwave oven',
    lastTime: '08:52 p.m.',
  },
  {
    displayName: 'Benny Rogahn',
    picture: 'https://cdn.fakercloud.com/avatars/lvovenok_128.jpg',
    lastMessage: 'internet refrigerator',
    lastTime: '02:21 p.m.',
  },
  {
    displayName: 'Erick Swaniawski',
    picture: 'https://cdn.fakercloud.com/avatars/borantula_128.jpg',
    lastMessage: 'garbage disposal unit',
    lastTime: '04:55 a.m.',
  },
  {
    displayName: 'Anne Streich',
    picture: 'https://cdn.fakercloud.com/avatars/charliecwaite_128.jpg',
    lastMessage: 'beehive oven',
    lastTime: '01:44 a.m.',
  },
  {
    displayName: 'Mr. Claude Schimmel',
    picture: 'https://cdn.fakercloud.com/avatars/dudestein_128.jpg',
    lastMessage: 'water cooler',
    lastTime: '12:27 p.m.',
  },
  {
    displayName: 'Dallas Barton V',
    picture: 'https://cdn.fakercloud.com/avatars/pechkinator_128.jpg',
    lastMessage: 'kitchener range',
    lastTime: '10:23 a.m.',
  },
  {
    displayName: 'Ronnie Emard DDS',
    picture: 'https://cdn.fakercloud.com/avatars/BroumiYoussef_128.jpg',
    lastMessage: 'air ioniser',
    lastTime: '01:29 p.m.',
  },
  {
    displayName: 'Eduardo Weber',
    picture: 'https://cdn.fakercloud.com/avatars/justinrob_128.jpg',
    lastMessage: 'instant hot water dispenser',
    lastTime: '06:25 a.m.',
  },
  {
    displayName: 'Molly Gibson',
    picture: 'https://cdn.fakercloud.com/avatars/jeremymouton_128.jpg',
    lastMessage: 'slow cooker',
    lastTime: '03:31 p.m.',
  },
  {
    displayName: 'Marcia Friesen',
    picture: 'https://cdn.fakercloud.com/avatars/sharvin_128.jpg',
    lastMessage: 'corn roaster',
    lastTime: '03:19 p.m.',
  },
  {
    displayName: 'Wilbur Runolfsson',
    picture: 'https://cdn.fakercloud.com/avatars/layerssss_128.jpg',
    lastMessage: 'sewing machine',
    lastTime: '07:38 p.m.',
  },
  {
    displayName: 'Louis Wisozk',
    picture: 'https://cdn.fakercloud.com/avatars/chadami_128.jpg',
    lastMessage: 'trivet',
    lastTime: '08:04 p.m.',
  },
  {
    displayName: 'Shirley Steuber',
    picture: 'https://cdn.fakercloud.com/avatars/imammuht_128.jpg',
    lastMessage: 'vaporizer',
    lastTime: '08:05 p.m.',
  },
  {
    displayName: 'Leslie Purdy Jr.',
    picture: 'https://cdn.fakercloud.com/avatars/thomasschrijer_128.jpg',
    lastMessage: 'back boiler',
    lastTime: '03:46 p.m.',
  },
  {
    displayName: 'Edward Jast',
    picture: 'https://cdn.fakercloud.com/avatars/kucingbelang4_128.jpg',
    lastMessage: 'kimchi refrigerator',
    lastTime: '05:59 a.m.',
  },
  {
    displayName: 'Ruby Feest',
    picture: 'https://cdn.fakercloud.com/avatars/muringa_128.jpg',
    lastMessage: 'pressure fryer',
    lastTime: '11:38 a.m.',
  },
  {
    displayName: 'Iris Kunze',
    picture: 'https://cdn.fakercloud.com/avatars/andreas_pr_128.jpg',
    lastMessage: 'boiler',
    lastTime: '03:22 p.m.',
  },
  {
    displayName: 'Vera Torp V',
    picture: 'https://cdn.fakercloud.com/avatars/eddiechen_128.jpg',
    lastMessage: 'clothes dryer',
    lastTime: '11:06 p.m.',
  },
  {
    displayName: 'Latoya Thiel',
    picture: 'https://cdn.fakercloud.com/avatars/layerssss_128.jpg',
    lastMessage: 'window fan',
    lastTime: '05:38 a.m.',
  },
  {
    displayName: 'Anita Nienow',
    picture: 'https://cdn.fakercloud.com/avatars/borantula_128.jpg',
    lastMessage: 'halogen oven',
    lastTime: '03:31 a.m.',
  },
  {
    displayName: 'Melody Schaefer',
    picture: 'https://cdn.fakercloud.com/avatars/BryanHorsey_128.jpg',
    lastMessage: 'bachelor griller',
    lastTime: '05:19 a.m.',
  },
  {
    displayName: 'Kerry Durgan',
    picture: 'https://cdn.fakercloud.com/avatars/louis_currie_128.jpg',
    lastMessage: 'popcorn maker',
    lastTime: '10:29 a.m.',
  },
  {
    displayName: 'Greg Runolfsdottir',
    picture: 'https://cdn.fakercloud.com/avatars/dmitriychuta_128.jpg',
    lastMessage: 'rice cooker',
    lastTime: '06:06 p.m.',
  },
  {
    displayName: "Guadalupe O'Keefe",
    picture: 'https://cdn.fakercloud.com/avatars/ashocka18_128.jpg',
    lastMessage: 'waffle iron',
    lastTime: '03:24 a.m.',
  },
  {
    displayName: 'Sue Stokes DVM',
    picture: 'https://cdn.fakercloud.com/avatars/therealmarvin_128.jpg',
    lastMessage: 'stove',
    lastTime: '11:09 p.m.',
  },
  {
    displayName: 'Julius Wyman V',
    picture: 'https://cdn.fakercloud.com/avatars/konus_128.jpg',
    lastMessage: 'wet grinder',
    lastTime: '01:38 p.m.',
  },
  {
    displayName: 'Dr. Terrell Prohaska',
    picture: 'https://cdn.fakercloud.com/avatars/anjhero_128.jpg',
    lastMessage: 'swamp cooler',
    lastTime: '08:19 a.m.',
  },
  {
    displayName: "Kristy O'Conner",
    picture: 'https://cdn.fakercloud.com/avatars/roxanejammet_128.jpg',
    lastMessage: 'icebox',
    lastTime: '02:08 p.m.',
  },
  {
    displayName: 'Karen Robel',
    picture: 'https://cdn.fakercloud.com/avatars/stevedesigner_128.jpg',
    lastMessage: 'oven',
    lastTime: '06:00 a.m.',
  },
  {
    displayName: 'Johnathan Braun',
    picture: 'https://cdn.fakercloud.com/avatars/charlesrpratt_128.jpg',
    lastMessage: 'soy milk maker',
    lastTime: '04:05 p.m.',
  },
  {
    displayName: 'Miss Leslie Keeling',
    picture: 'https://cdn.fakercloud.com/avatars/mymyboy_128.jpg',
    lastMessage: 'washing machine',
    lastTime: '04:50 p.m.',
  },
  {
    displayName: 'Joanne Jenkins',
    picture: 'https://cdn.fakercloud.com/avatars/joetruesdell_128.jpg',
    lastMessage: 'water cooker',
    lastTime: '08:14 p.m.',
  },
  {
    displayName: 'Mrs. Danny Jacobs',
    picture: 'https://cdn.fakercloud.com/avatars/joetruesdell_128.jpg',
    lastMessage: 'HVAC',
    lastTime: '04:30 p.m.',
  },
  {
    displayName: 'Monica Ernser',
    picture: 'https://cdn.fakercloud.com/avatars/wake_gs_128.jpg',
    lastMessage: 'combo washer dryer',
    lastTime: '09:51 p.m.',
  },
  {
    displayName: 'Dr. Conrad Greenfelder',
    picture: 'https://cdn.fakercloud.com/avatars/pifagor_128.jpg',
    lastMessage: 'rotisserie',
    lastTime: '12:24 p.m.',
  },
  {
    displayName: 'Dominick Rau',
    picture: 'https://cdn.fakercloud.com/avatars/markretzloff_128.jpg',
    lastMessage: 'aroma lamp',
    lastTime: '03:04 a.m.',
  },
  {
    displayName: 'Marcos Roob',
    picture: 'https://cdn.fakercloud.com/avatars/teeragit_128.jpg',
    lastMessage: 'energy regulator',
    lastTime: '05:50 a.m.',
  },
  {
    displayName: 'Dr. Raul Beahan',
    picture: 'https://cdn.fakercloud.com/avatars/jwalter14_128.jpg',
    lastMessage: 'window fan',
    lastTime: '07:51 p.m.',
  },
  {
    displayName: 'Leslie Breitenberg',
    picture: 'https://cdn.fakercloud.com/avatars/guiiipontes_128.jpg',
    lastMessage: 'oven',
    lastTime: '10:41 a.m.',
  },
  {
    displayName: 'Dr. Ricky Gislason',
    picture: 'https://cdn.fakercloud.com/avatars/colirpixoil_128.jpg',
    lastMessage: 'mousetrap',
    lastTime: '08:02 p.m.',
  },
  {
    displayName: 'Matthew Wyman',
    picture: 'https://cdn.fakercloud.com/avatars/hanna_smi_128.jpg',
    lastMessage: 'boiler',
    lastTime: '06:44 p.m.',
  },
  {
    displayName: 'Malcolm Lebsack',
    picture: 'https://cdn.fakercloud.com/avatars/hsinyo23_128.jpg',
    lastMessage: 'tie press',
    lastTime: '06:21 a.m.',
  },
  {
    displayName: 'Dr. Melissa Schimmel',
    picture: 'https://cdn.fakercloud.com/avatars/gaborenton_128.jpg',
    lastMessage: 'water cooker',
    lastTime: '07:55 a.m.',
  },
  {
    displayName: 'Mr. Connie Fisher',
    picture: 'https://cdn.fakercloud.com/avatars/lepetitogre_128.jpg',
    lastMessage: 'butane torch',
    lastTime: '07:33 a.m.',
  },
  {
    displayName: 'Opal Ortiz Sr.',
    picture: 'https://cdn.fakercloud.com/avatars/dutchnadia_128.jpg',
    lastMessage: 'back boiler',
    lastTime: '05:13 p.m.',
  },
  {
    displayName: 'Katherine Wilderman',
    picture: 'https://cdn.fakercloud.com/avatars/gabrielrosser_128.jpg',
    lastMessage: 'slow cooker',
    lastTime: '10:03 a.m.',
  },
  {
    displayName: 'Lorenzo Muller',
    picture: 'https://cdn.fakercloud.com/avatars/naitanamoreno_128.jpg',
    lastMessage: 'beehive oven',
    lastTime: '10:07 p.m.',
  },
  {
    displayName: 'Hubert Hoeger PhD',
    picture: 'https://cdn.fakercloud.com/avatars/brenmurrell_128.jpg',
    lastMessage: 'reflector oven',
    lastTime: '09:05 a.m.',
  },
  {
    displayName: 'Charlotte Romaguera Sr.',
    picture: 'https://cdn.fakercloud.com/avatars/kevinjohndayy_128.jpg',
    lastMessage: 'coffeemaker',
    lastTime: '09:24 p.m.',
  },
  {
    displayName: 'Jacob Lockman',
    picture: 'https://cdn.fakercloud.com/avatars/jeremery_128.jpg',
    lastMessage: 'HVAC',
    lastTime: '03:07 a.m.',
  },
  {
    displayName: 'Krista Yost',
    picture: 'https://cdn.fakercloud.com/avatars/rmlewisuk_128.jpg',
    lastMessage: 'patio heater',
    lastTime: '07:56 a.m.',
  },
  {
    displayName: 'Elsa Cummerata',
    picture: 'https://cdn.fakercloud.com/avatars/_ragzor_128.jpg',
    lastMessage: 'set-n-forget cooker',
    lastTime: '09:49 p.m.',
  },
  {
    displayName: 'Clay Rowe',
    picture: 'https://cdn.fakercloud.com/avatars/fjaguero_128.jpg',
    lastMessage: 'slow cooker',
    lastTime: '09:34 a.m.',
  },
  {
    displayName: 'Billy Lebsack',
    picture: 'https://cdn.fakercloud.com/avatars/davidhemphill_128.jpg',
    lastMessage: 'crepe maker',
    lastTime: '02:37 p.m.',
  },
  {
    displayName: 'Shelley Parisian',
    picture: 'https://cdn.fakercloud.com/avatars/kapaluccio_128.jpg',
    lastMessage: 'electric cooker',
    lastTime: '12:44 p.m.',
  },
  {
    displayName: 'Becky Smitham',
    picture: 'https://cdn.fakercloud.com/avatars/y2graphic_128.jpg',
    lastMessage: 'HVAC',
    lastTime: '11:20 p.m.',
  },
  {
    displayName: 'Beth Torphy',
    picture: 'https://cdn.fakercloud.com/avatars/rahmeen_128.jpg',
    lastMessage: 'self-cleaning oven',
    lastTime: '09:11 p.m.',
  },
  {
    displayName: 'Mr. Judy Gibson',
    picture: 'https://cdn.fakercloud.com/avatars/mikemai2awesome_128.jpg',
    lastMessage: 'patio heater',
    lastTime: '03:14 a.m.',
  },
  {
    displayName: 'Lillian Langworth',
    picture: 'https://cdn.fakercloud.com/avatars/swaplord_128.jpg',
    lastMessage: 'self-cleaning oven',
    lastTime: '09:15 a.m.',
  },
  {
    displayName: 'Mercedes Torp',
    picture: 'https://cdn.fakercloud.com/avatars/mbilderbach_128.jpg',
    lastMessage: 'wood-fired oven',
    lastTime: '02:53 p.m.',
  },
  {
    displayName: 'Clay Hammes',
    picture: 'https://cdn.fakercloud.com/avatars/josecarlospsh_128.jpg',
    lastMessage: 'flattop grill',
    lastTime: '04:17 p.m.',
  },
  {
    displayName: 'Tracy Hodkiewicz',
    picture: 'https://cdn.fakercloud.com/avatars/liminha_128.jpg',
    lastMessage: 'flame supervision device',
    lastTime: '01:48 p.m.',
  },
  {
    displayName: 'Ernestine Halvorson PhD',
    picture: 'https://cdn.fakercloud.com/avatars/madysondesigns_128.jpg',
    lastMessage: 'beverage opener',
    lastTime: '11:13 p.m.',
  },
  {
    displayName: 'Wade Lang',
    picture: 'https://cdn.fakercloud.com/avatars/low_res_128.jpg',
    lastMessage: 'embroidery machine',
    lastTime: '10:57 p.m.',
  },
  {
    displayName: 'Belinda Crist',
    picture: 'https://cdn.fakercloud.com/avatars/chanpory_128.jpg',
    lastMessage: 'central vacuum cleaner',
    lastTime: '10:03 a.m.',
  },
  {
    displayName: 'Kathy Halvorson',
    picture: 'https://cdn.fakercloud.com/avatars/andrewabogado_128.jpg',
    lastMessage: 'hair iron',
    lastTime: '09:33 p.m.',
  },
  {
    displayName: 'Wayne Schaefer',
    picture: 'https://cdn.fakercloud.com/avatars/mrmartineau_128.jpg',
    lastMessage: 'sump pump',
    lastTime: '06:50 p.m.',
  },
  {
    displayName: 'Jan Harris',
    picture: 'https://cdn.fakercloud.com/avatars/webtanya_128.jpg',
    lastMessage: 'hair iron',
    lastTime: '01:01 a.m.',
  },
  {
    displayName: 'Chelsea Abshire IV',
    picture: 'https://cdn.fakercloud.com/avatars/marklamb_128.jpg',
    lastMessage: 'tandoor',
    lastTime: '05:37 p.m.',
  },
  {
    displayName: 'Miss Charlotte Kub',
    picture: 'https://cdn.fakercloud.com/avatars/lawlbwoy_128.jpg',
    lastMessage: 'micathermic heater',
    lastTime: '04:42 a.m.',
  },
  {
    displayName: 'Mary Senger',
    picture: 'https://cdn.fakercloud.com/avatars/pehamondello_128.jpg',
    lastMessage: 'wet grinder',
    lastTime: '03:22 a.m.',
  },
  {
    displayName: 'Adrienne Ankunding',
    picture: 'https://cdn.fakercloud.com/avatars/davidbaldie_128.jpg',
    lastMessage: 'kitchener range',
    lastTime: '03:57 a.m.',
  },
  {
    displayName: 'Clark Okuneva',
    picture: 'https://cdn.fakercloud.com/avatars/adammarsbar_128.jpg',
    lastMessage: 'aroma lamp',
    lastTime: '10:48 p.m.',
  },
  {
    displayName: 'Duane Jacobi',
    picture: 'https://cdn.fakercloud.com/avatars/charliecwaite_128.jpg',
    lastMessage: 'deep fryer',
    lastTime: '03:34 a.m.',
  },
  {
    displayName: 'Grady Hansen',
    picture: 'https://cdn.fakercloud.com/avatars/michalhron_128.jpg',
    lastMessage: 'beehive oven',
    lastTime: '08:11 a.m.',
  },
  {
    displayName: 'Kristine Ortiz',
    picture: 'https://cdn.fakercloud.com/avatars/hsinyo23_128.jpg',
    lastMessage: 'tandoor',
    lastTime: '03:34 p.m.',
  },
  {
    displayName: 'Eleanor Kling',
    picture: 'https://cdn.fakercloud.com/avatars/nelshd_128.jpg',
    lastMessage: 'corn roaster',
    lastTime: '04:47 a.m.',
  },
  {
    displayName: 'Katrina Bergnaum',
    picture: 'https://cdn.fakercloud.com/avatars/salvafc_128.jpg',
    lastMessage: 'microwave oven',
    lastTime: '02:08 a.m.',
  },
  {
    displayName: 'Dr. Roy Schulist',
    picture: 'https://cdn.fakercloud.com/avatars/baumann_alex_128.jpg',
    lastMessage: 'earth oven',
    lastTime: '03:58 p.m.',
  },
  {
    displayName: 'Stewart Bartoletti',
    picture: 'https://cdn.fakercloud.com/avatars/salvafc_128.jpg',
    lastMessage: 'fire pot',
    lastTime: '10:12 a.m.',
  },
  {
    displayName: "Stanley O'Hara",
    picture: 'https://cdn.fakercloud.com/avatars/marcoramires_128.jpg',
    lastMessage: 'window fan',
    lastTime: '01:50 p.m.',
  },
  {
    displayName: 'Dean Tromp',
    picture: 'https://cdn.fakercloud.com/avatars/joreira_128.jpg',
    lastMessage: 'central vacuum cleaner',
    lastTime: '02:46 p.m.',
  },
  {
    displayName: 'Inez Runolfsdottir',
    picture: 'https://cdn.fakercloud.com/avatars/oaktreemedia_128.jpg',
    lastMessage: 'convection microwave',
    lastTime: '11:11 a.m.',
  },
  {
    displayName: 'Ruben Emard',
    picture: 'https://cdn.fakercloud.com/avatars/maximsorokin_128.jpg',
    lastMessage: 'electric cooker',
    lastTime: '04:31 a.m.',
  },
];
